version: "2.1"

networks:
  nginx:

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "goaccess"
      - "website"
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1001
    networks:
      - nginx
    volumes:
      - /data/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /data/docker/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - /data/docker/nginx/ffdhe2048.txt:/etc/nginx/ffdhe2048.txt:ro
      - /data/docker/nginx/sites/:/etc/nginx/sites:ro
      - /data/docker/nginx/logs/:/var/log/nginx/
      - /data/docker/nginx/include.d/:/etc/nginx/include.d/:ro
      - /data/docker/nginx/no-access-robots.txt:/var/www/no-access-robots.txt:ro
      - /data/docker/goaccess/real-time/:/var/www/real-time-stats/:ro
      - /data/docker/letsencrypt/etc/letsencrypt:/etc/letsencrypt:ro

  goaccess:
    container_name: goaccess
    image: allinurl/goaccess:latest
    restart: unless-stopped
    command: /var/log/nginx/access.log -o /var/www/real-time-stats/index.html --log-format=COMBINED --real-time-html --ws-url=wss://stats.josephduffy.co.uk:443/ws --port 7890
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1001
    networks:
      - nginx
    volumes:
      - /data/docker/nginx/logs/:/var/log/nginx/
      - /data/docker/goaccess/real-time/:/var/www/real-time-stats/

  letsencrypt:
    container_name: letsencrypt
    image: adferrand/letsencrypt-dns:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1001
      - LETSENCRYPT_USER_MAIL
      - LEXICON_PROVIDER=cloudflare
      - LEXICON_CLOUDFLARE_USERNAME
      - LEXICON_CLOUDFLARE_TOKEN
    volumes:
      - /data/docker/letsencrypt/etc/letsencrypt:/etc/letsencrypt
      - /data/docker/letsencrypt/domains.conf:/etc/letsencrypt/domains.conf
      - /var/run/docker.sock:/var/run/docker.sock # to support reloading nginx

  website:
    container_name: website
    build:
        context: ../josephduffy.co.uk
        dockerfile: Dockerfile
        args:
          - GITHUB_ACCESS_TOKEN
    restart: unless-stopped
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1001
      - GITHUB_ACCESS_TOKEN
    networks:
        - nginx
