name: Deploy

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      env:
        WebsiteEnv: ${{ secrets.WebsiteEnv }}
        LetsEncryptEnv: ${{ secrets.LetsEncryptEnv }}
        HTPASSWD_CONTENTS: ${{ secrets.HTPASSWD_CONTENTS }}
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          #!/bin/bash

          if [[ -d "josephduffy.co.uk" ]]; then
            cd josephduffy.co.uk || exit
            git pull
            cd ..
          else
            git clone --single-branch --branch next-js https://github.com/JosephDuffy/josephduffy.co.uk.git
          fi

          if [[ -d "webserver-deploy" ]]; then
            cd webserver-deploy || exit
            git pull
          else
            git clone https://github.com/JosephDuffy/webserver-deploy.git
            cd webserver-deploy || exit
          fi

          echo "$WebsiteEnv" > .env.website
          echo "$LetsEncryptEnv" > .env.letsencrypt
          echo "$HTPASSWD_CONTENTS" > nginx/.htpasswd

          env HTTP_PORT=80 HTTPS_PORT=443 docker-compose --file docker-compose.yml up --detach --build
          docker exec -it nginx nginx -s reload

          git checkout -- .env.website
          git checkout -- .env.letsencrypt
