name: Deploy

on:
  push:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        envs: GITHUB_ACCESS_TOKEN
        script: |
          TEMP_DIR=$(mktemp -d)

          function cleanup {
            rm -r "$TEMP_DIR"
          }

          cd "$TEMP_DIR" || exit

          trap cleanup EXIT

          git clone --depth 1 https://github.com/JosephDuffy/josephduffy.co.uk.git
          git clone --depth 1 https://github.com/JosephDuffy/webserver-deploy.git
          cd webserver-deploy || exit

          if [[ -f ~/.config/stats.josephduffy.co.uk/.htaccess ]]; then
            cp ~/.config/stats.josephduffy.co.uk/.htaccess ./nginx/.htpasswd
          else
            >&2 echo "No htaccess file found"
            exit 1
          fi

          env GITHUB_ACCESS_TOKEN="$GITHUB_ACCESS_TOKEN" docker-compose build --no-cache website
          env GITHUB_ACCESS_TOKEN="$GITHUB_ACCESS_TOKEN" docker-compose up --detach --build
          docker exec nginx nginx -s reload
