name: Deploy

on:
  push:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        envs: GITHUB_ACCESS_TOKEN
        script: |
          if [[ -d "josephduffy.co.uk" ]]; then
            cd josephduffy.co.uk || exit
            git pull
            cd ..
          else
            git clone --single-branch --branch master https://github.com/JosephDuffy/josephduffy.co.uk.git
          fi

          if [[ -d "webserver-deploy" ]]; then
            cd webserver-deploy || exit
            git pull
          else
            git clone https://github.com/JosephDuffy/webserver-deploy.git
            cd webserver-deploy || exit
          fi

          env GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN docker-compose build --no-cache website
          env GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN docker-compose up --detach --build
          docker exec nginx nginx -s reload
