name: Deploy

on:
  push:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          script: |
            source ~/.profile

            TEMP_DIR=$(mktemp -d)

            function cleanup {
              rm -r "$TEMP_DIR"
            }

            cd "$TEMP_DIR" || exit

            trap cleanup EXIT
            git clone --depth 1 https://github.com/JosephDuffy/webserver-deploy.git
            cd webserver-deploy || exit

            mkdir -p /data/docker

            cp -R ./data/docker/. /data/docker/
            cd /data/docker/

            docker volume create --name=caddy_data
            docker-compose pull
            docker-compose up --detach --build --remove-orphans
            docker system prune --force

            if [[ $(docker inspect caddy --format='{{.State.Running}}') == "true" ]]; then
              docker exec -w /etc/caddy caddy caddy reload
            fi
