name: Deploy

on:
  push:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          source ~/.profile

          TEMP_DIR=$(mktemp -d)

          function cleanup {
            rm -r "$TEMP_DIR"
          }

          cd "$TEMP_DIR" || exit

          trap cleanup EXIT
          git clone --depth 1 https://github.com/JosephDuffy/webserver-deploy.git
          cd webserver-deploy || exit

          mkdir -p /data/docker

          cp -R ./data/docker/ /data/docker
          cd /data/docker

          docker-compose up --detach
          docker system prune --force
