name: Deploy

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      env:
        WebsiteEnv: ${{ secrets.WebsiteEnv }}
        LetsEncryptEnv: ${{ secrets.LetsEncryptEnv }}
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          if [ -d "josephduffy.co.uk" ]; then
            cd josephduffy.co.uk
            git pull
            cd ..
          else
            git clone --single-branch --branch next-js git@github.com:JosephDuffy/josephduffy.co.uk.git
          fi

          if [ -d webserver-deploy ]; then
            cd webserver-deploy
            git pull
          else
            git clone git@github.com:JosephDuffy/webserver-deploy.git
            cd webserver-deploy
          fi

          echo "$WebsiteEnv" >> .env.website
          echo "$LetsEncryptEnv" >> .env.letsencrypt
          echo "$HTPASSWD_COTENTS" >> nginx/.htpasswd

          env HTTP_PORT=81 HTTPS_PORT=444 docker-compose --file docker-compose.yml up --detach --remove-orphans
          docker exec -it nginx nginx -s reload

          git checkout -- .env.website
          git checkout -- .env.letsencrypt
          git checkout -- nginx/.htpasswd
