name: Update contact.josephduffy.co.uk

on:
  repository_dispatch:
    types: [update_contact-josephduffy-co-uk]

jobs:
  update:
    name: Update contact.josephduffy.co.uk
    runs-on: ubuntu-latest
    steps:
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          script: |
            source ~/.profile
            cd /data/docker/
            docker-compose --verbose pull contact-josephduffy-co-uk
            docker-compose up --detach contact-josephduffy-co-uk
            docker image prune --force
